// Code generated by go generate; DO NOT EDIT.

package _gen

import (
	"fmt"

	"sacer/go/entry"
	"sacer/go/entry/file"
	"sacer/go/entry/info"
	"sacer/go/entry/tools"
	"time"
)

func (e *_gen) Type() string {
	return "_gen"
}

func (e *_gen) Parent() entry.Entry {
	return e.parent
}

func (e *_gen) File() *file.File {
	return e.file
}

func (e *_gen) Id() int64 {
	return e.date.Unix()
}

func (e *_gen) Timestamp() string {
	return e.date.Format(tools.Timestamp)
}

func (e *_gen) Hash() string {
	return tools.ToB16(e.date)
}

func (e *_gen) HashShort() string {
	return tools.ShortenHash(e.Hash())
}

func (e *_gen) Date() time.Time {
	return e.date
}

func (e *_gen) Info() info.Info {
	return e.info
}

func (e *_gen) Title(lang string) string {
	if title := e.info.Title(lang); title != "" {
		return title
	}
	return e.HashShort()
}

func (e *_gen) Slug(lang string) string {
	if slug := e.info.Slug(lang); slug != "" {
		return slug
	}
	return tools.Normalize(e.info.Title(lang))
}

func (e *_gen) MediaObject() bool {
	return e.Type() != "audio" && entry.IsBlob(e)
}

func (e *_gen) ObjectType() string {
	if e.MediaObject() {
		return "mob"
	}
	return "tob"
}

func (e *_gen) SetParent(parent entry.Entry) {
	e.parent = parent
}

func (e *_gen) SetInfo(inf info.Info) {
	e.info = inf
}

func (e *_gen) Path(lang string) string {
	return fmt.Sprintf("%v/%v", e.parent.Path(lang), e.Slug(lang))
}

// This recursive function call will be caught by a Tree type. For now, all
// further up parent entries are exclusively of type Tree.
func (e *_gen) Section() string {
	return e.Parent().Section()
}

func (e *_gen) Perma(lang string) string {
	if e.parent.Type() == "set" {
		return e.parent.Perma(lang)
	}

	name := e.Hash()
	if slug := e.Slug(lang); slug != "" {
		name = fmt.Sprintf("%v-%v", slug, e.Hash())
	}

	switch e.Section() {
	case "kine":
		return fmt.Sprintf(
			"/%v/%v/%v",
			tools.KineName[lang],
			e.Date().Format("06-01"),
			fmt.Sprintf("%v-%v", e.Date().Format("02"), name),
		)
	case "index":
		if e.Type() != "image" {
			return fmt.Sprintf("%v#%v", e.parent.Perma(lang), tools.Normalize(e.Title(lang)))
		}
	}

	return fmt.Sprintf("%v/%v", e.parent.Path(lang), name)
}
