// Code generated by go generate; DO NOT EDIT.

package media 

import (
	"fmt"
	"stferal/go/entry"
	"stferal/go/entry/helper"
	"stferal/go/entry/types/media/text"
)

func NewMedia(path string, parent interface{}) (*entry.Entry, error) {
	return entry.NewEntry(path, parent, newMediaObj)
}

func newMediaObj(path string) (interface{}, error) {
	switch helper.FileType(path) {
	case "text":
		return text.New(path)
	}
	return nil, fmt.Errorf("invalid entry type: %v", path)
}
