// +build ignore

{{define "out" -}}
// Code generated by go generate; DO NOT EDIT.

package {{pkgName .}}

import (
	"stferal/go/entry"
	"stferal/go/entry/helper"
	"stferal/go/entry/parts/file"
	"stferal/go/entry/parts/info"
	"time"
)

func {{receiver .}} Parent() entry.Entry {
	return e.parent
}

func {{receiver .}} File() *file.File {
	return e.file
}

func {{receiver .}} Id() string {
	return e.date.Format(helper.Timestamp)
}

func {{receiver .}} Hash() string {
	return helper.ToB16(e.date)
}

func {{receiver .}} HashShort() string {
	return helper.ShortenHash(e.Hash())
}

func {{receiver .}} Title(lang string) string {
	if title := e.info.Title(lang); title != "" {
		return title
	}
	return e.HashShort()
}

func {{receiver .}} Date() time.Time {
	return e.date
}

func {{receiver .}} Info() info.Info {
	return e.info
}
{{end}}
