// +build ignore

{{define "main" -}}
// Code generated by go generate; DO NOT EDIT.

package entry

func NewEntry(path string, hold *Hold) (interface{}, error) {
	switch FileType(path) {
{{- range $, $name := .Media}}
		case "{{$name}}":
			return New{{title $name}}(path, hold)
{{- end}}
		case "dir":
			return NewSet(path, hold)
	}
	return nil, fmt.Errorf("invalid entry: %v", path)
}
{{end}}
