// Code generated by go generate; DO NOT EDIT.

package entry

func NewEl(path string, hold *Hold) (interface{}, error) {
	switch FileType(path) {
	case "audio":
		return NewAudio(path, hold)
	case "html":
		return NewHtml(path, hold)
	case "image":
		return NewImage(path, hold)
	case "text":
		return NewText(path, hold)
	case "video":
		return NewVideo(path, hold)
	case "dir":
		return NewSet(path, hold)
	}
	return NewFile(path, hold)
}
