// Code generated by go generate; DO NOT EDIT.

package entry

type Entry struct {
	Parent interface{}
	Object interface{}
}

func (e *Entry) O() interface{} {
	return e.Object
}

type Entries []*Entry

